// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
require('babel-core/register')

const chromedriver = require('chromedriver');
require('geckodriver')

const tesUrl = 'http://ninjaplus-web:5000'
const defaultTimeout = 15000

module.exports = {

  src_folders: ["tests"],

  page_objects_path: './pages',
  globals_path: './hooks/globals.js',

  webdriver: {
    start_process: true,
  },

  test_workers: {
    anabled: true, // testes em paralelo, vai depender da maquina virtual, processador.
    workers: 2 // quantidade de navegadores simultaneos
  },

  test_settings: {
    default: {
      launch_url: tesUrl,
      globals:{
        waitForConditionTimeout: defaultTimeout
      },

      webdriver:{
        server_path: chromedriver.path,
        port: 9515
      },

      desiredCapabilities: {
        browserName: "chrome"
      }
    },

    headless:{
      launch_url: tesUrl,
      globals:{
        waitForConditionTimeout: defaultTimeout
      },

      webdriver:{
        server_path: chromedriver.path,
        port: 9515
      },

      desiredCapabilities: {
        browserName: "chrome",
        chromeOptions: {
          w3c: false,
          args: ['--headless', '--no-sandbox']
        }
      }
    },

    firefox:{

      launch_url: tesUrl,
      globals:{
        waitForConditionTimeout: defaultTimeout
      },

      webdriver:{
        server_path: '.\\node_modules\\.bin\\geckodriver.cmd',
        port: 4444
      },

      desiredCapabilities: {
        browserName: "firefox",
        acceptInsecureCerts: true
      }
    },

    stage:{
      launch_url: "http://stage.zombieplus.com.br"
    }
  }
}

